# Generated by Django 5.1.1 on 2024-09-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tision', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
