# Generated by Django 5.1.1 on 2024-09-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tision', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field=20, null=True, upload_to='C:\\Users\\cassidy\\Desktop\\tision\\backend\\back_end\\media', width_field=20),
        ),
    ]
