# Generated by Django 5.1.1 on 2024-09-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tision', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\cassidy\\Desktop\\tision\\backend\\back_end\\media'),
        ),
    ]
